_id: 66deee33a6fbf1002b01c522
title: Singleplay Past Matches
description: Describe your new bucket
icon: important_devices
primary: name
readOnly: false
history: false
properties:
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
  user:
    type: relation
    title: user
    description: Description of the user input
    options:
      position: bottom
      index: true
    relationType: onetoone
    bucketId: 605c9480e9960e002c278191
    dependent: false
    primary: name
  user_points:
    type: number
    title: user_points
    description: Description of the user_points input
    options:
      position: bottom
      index: true
  start_time:
    type: date
    title: start_time
    description: Description of the start_time input
    options:
      position: bottom
      index: true
  end_time:
    type: date
    title: end_time
    description: Description of the end_time input
    options:
      position: bottom
      index: true
  user_is_free:
    type: boolean
    title: user_is_free
    description: Description of the user_is_free input
    options:
      position: bottom
      index: true
    default: false
  duel_id:
    type: string
    title: duel_id
    description: Description of the duel_id input
    options:
      position: bottom
  user_answers:
    type: array
    title: user_answers
    description: Description of the user_answers input
    options:
      position: bottom
    items:
      title: Title of the items
      type: string
acl:
  write: true==true
  read: true==true
order: 9
category: Singleplay
