_id: 60bf26f4c48b36002dd87e01
title: Mailer - Requests
description: Describe your new bucket
icon: view_stream
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
  emails:
    type: array
    title: emails
    description: Description of the emails input
    options:
      position: bottom
    items:
      title: Title of the items
      type: string
  template:
    type: string
    title: template
    description: Description of the template input
    options:
      position: bottom
  variables:
    type: textarea
    title: variables
    description: Description of the variables input
    options:
      position: bottom
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
  bucket_id:
    type: string
    title: bucket_id
    description: Description of the bucket_id input
    options:
      position: bottom
  report_type:
    type: number
    title: report_type
    description: Description of the report_type input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 13
