_id: 66e033baa6fbf1002b02aa21
name: Singleplay Insert Past Matches
language: javascript
timeout: 60
triggers:
  insertPastMatchFromServer:
    options:
      method: Post
      path: /insertPastMatchFromServer
      preflight: true
    type: http
    active: true
  removeServerInfoExternal:
    options:
      method: Post
      path: /removeServerInfoExternal
      preflight: true
    type: http
    active: true
  singlePlayinsertPastMatchAWS:
    options:
      method: Post
      path: /insertPastMatchFromAWSServer
      preflight: true
    type: http
    active: true
env:
  OPERATION_KEY: "{OPERATION_KEY}"
  USER_BUCKET_ID: "{USER_BUCKET_ID}"
  PAST_DUELS_BUCKET_ID: "{PAST_DUELS_BUCKET_ID}"
  SERVERS_INFO: "{SERVERS_INFO}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
