_id: 60bf26f4c48b36002dd87e00
title: Mailer - Templates
description: Describe your new bucket
icon: view_stream
primary: title
readOnly: false
history: false
properties:
  title:
    type: string
    title: title
    description: Title of the row
    options:
      position: left
  description:
    type: textarea
    title: description
    description: Description of the row
    options:
      position: right
  subject:
    type: string
    title: subject
    description: Description of the subject input
    options:
      position: bottom
  template:
    type: string
    title: template
    description: Description of the template input
    options:
      position: bottom
  content:
    type: richtext
    title: content
    description: Description of the content input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 29
