_id: 60d9c90438158a002c3924dd
name: User Point Cleaner
language: javascript
timeout: 40
triggers:
  clearUserPoint:
    options:
      timezone: Europe/Istanbul
      frequency: 0 0 * * 1
    type: schedule
    active: false
  clearBotPoint:
    options:
      timezone: UTC
      frequency: "* * * * *"
    type: schedule
    active: true
  updateConfirmCode:
    options:
      frequency: "* * * * *"
      timezone: Europe/Istanbul
    type: schedule
    active: true
  getLast3MonthsPlayUser:
    options:
      method: Get
      path: /getLast3MonthsPlayUser1
      preflight: true
    type: http
    active: true
env:
  USER_BUCKET_ID: "{USER_BUCKET_ID}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
  CONFIRMATION_CODE_BUCKET_ID: "{CONFIRMATION_CODE_BUCKET_ID}"
memoryLimit: 100
