_id: 60d9cb8b38158a002c39254d
name: Fast Login & Register
language: javascript
timeout: 40
triggers:
  login:
    options:
      method: Post
      path: /fastLogin
      preflight: true
    type: http
    active: true
  register:
    options:
      method: Post
      path: /fastRegister
      preflight: true
    type: http
    active: true
  getMyIp:
    options:
      path: /getMyIp
      method: Get
      preflight: true
    type: http
    active: true
  testSeamlessTokenValidate:
    options:
      method: Get
      path: /testSeamlessTokenValidate
      preflight: true
    type: http
    active: false
env:
  FASTLOGIN_SECRET_KEY: "{FASTLOGIN_SECRET_KEY}"
  FASTLOGIN_SERVICE_ID: "{FASTLOGIN_SERVICE_ID}"
  SECRET_API_KEY: "{SECRET_API_KEY}"
  USER_POLICY: "{USER_POLICY}"
  USER_BUCKET_ID: "{USER_BUCKET_ID}"
  PASSWORD_SALT: "{PASSWORD_SALT}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
memoryLimit: 100
