_id: 605c9480e9960e002c278191
title: User
description: Describe your new bucket
icon: view_stream
primary: name
readOnly: false
history: false
properties:
  identity:
    type: string
    title: identity
    description: Description of the identity input
    options:
      position: bottom
      index: true
  name:
    type: string
    title: name
    description: Description of the name input
    options:
      position: bottom
  profile_photo:
    type: storage
    title: profile_photo
    description: Description of the profile_photo input
    options:
      position: bottom
  perm_accept:
    type: boolean
    title: perm_accept
    description: Description of the perm_accept input
    options:
      position: bottom
    default: false
  elo:
    type: number
    title: elo
    description: Description of the elo input
    options:
      position: bottom
    default: 0
    minimum: 0
  bot:
    type: boolean
    title: bot
    description: Description of the bot input
    options:
      position: bottom
      index: true
    default: false
  total_point:
    type: number
    title: total_point
    description: Description of the total_point input
    options:
      position: bottom
    default: 0
  weekly_point:
    type: number
    title: weekly_point
    description: Description of the weekly_point input
    options:
      position: bottom
      index: true
    default: 0
  win_count:
    type: number
    title: win_count
    description: Description of the win_count input
    options:
      position: bottom
    default: 0
  lose_count:
    type: number
    title: lose_count
    description: Description of the lose_count input
    options:
      position: bottom
    default: 0
  free_play:
    type: boolean
    title: free_play
    description: Description of the free_play input
    options:
      position: bottom
    default: false
  available_play_count:
    type: number
    title: available_play_count
    description: Description of the available_play_count input
    options:
      position: bottom
    minimum: 0
    default: 0
  created_at:
    type: date
    title: created_at
    description: Description of the created_at input
    options:
      position: bottom
      index: true
  total_award:
    type: number
    title: total_award
    description: Description of the total_award input
    options:
      position: bottom
    minimum: 0
    default: 0
  avatar_color:
    type: string
    title: avatar_color
    description: Description of the avatar_color input
    options:
      position: bottom
  weekly_award:
    type: number
    title: weekly_award
    description: Description of the weekly_award input
    options:
      position: bottom
  avatar_id:
    type: number
    title: avatar_id
    description: Description of the avatar_id input
    options:
      position: bottom
  note:
    type: textarea
    title: note
    description: Description of the note input
    options:
      position: bottom
  draw_confirmated:
    type: boolean
    title: draw_confirmated
    description: Description of the draw_confirmated input
    options:
      position: bottom
    default: false
  op_note:
    type: array
    title: op_note
    description: Description of the op_note input
    options:
      position: bottom
    items:
      title: Title of the items
      type: object
      properties:
        sender:
          type: string
          title: sender
          description: Description of the sender input
          options:
            position: bottom
        note:
          type: textarea
          title: note
          description: Description of the note input
          options:
            position: bottom
        date:
          type: date
          title: date
          description: Description of the date input
          options:
            position: bottom
          default: :created_at
acl:
  write: true==true
  read: true==true
order: 15
