_id: 606c138f6b2647002c2fc497
title: Matchmaking
description: Describe your new bucket
icon: view_stream
primary: min_elo
readOnly: false
history: false
properties:
  user:
    type: relation
    title: user
    description: Description of the user input
    options:
      position: bottom
    relationType: onetoone
    bucketId: 605c9480e9960e002c278191
    dependent: false
    primary: name
  date:
    type: date
    title: date
    description: Description of the date input
    options:
      position: bottom
  min_elo:
    type: number
    title: min_elo
    description: Description of the min_elo input
    options:
      position: bottom
  max_elo:
    type: number
    title: max_elo
    description: Description of the max_elo input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 17
required:
  - user
