_id: 60d9c7f838158a002c3924b0
name: Check Finished Duels
language: javascript
timeout: 56.5
triggers:
  checkFinishedDuels:
    options:
      timezone: Europe/Istanbul
      frequency: "*/10 * * * * *"
    type: schedule
    active: false
  insertPastMatchFromServerMultiplayer:
    options:
      method: Post
      path: /insertPastMatchFromServerMultiplayer
      preflight: true
    type: http
    active: false
  removeServerInfoExternalMultiplayer:
    options:
      method: Post
      path: /removeServerInfoExternalMultiplayer
      preflight: true
    type: http
    active: false
  clearServerInfoBucket:
    options:
      timezone: UTC
      frequency: "* * * * *"
    type: schedule
    active: false
env:
  SECRET_API_KEY: "{SECRET_API_KEY}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
  DUEL_BUCKET_ID: "{DUEL_BUCKET_ID}"
  PAST_DUELS_BUCKET_ID: "{PAST_DUELS_BUCKET_ID}"
  USER_BUCKET_ID: "{USER_BUCKET_ID}"
  OPERATION_KEY: "{OPERATION_KEY}"
  SERVERS_INFO: "{SERVERS_INFO}"
memoryLimit: 100
