_id: 60d9ca5538158a002c392519
name: Add to Match Making
language: javascript
timeout: 40
triggers:
  addMatchMaking:
    options:
      method: Post
      path: /addMatchMaking
      preflight: true
    type: http
    active: true
env:
  MATCHMAKING_BUCKET_ID: "{MATCHMAKING_BUCKET_ID}"
  SECRET_API_KEY: "{SECRET_API_KEY}"
  USER_BUCKET_ID: "{USER_BUCKET_ID}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
  JWT_SECRET_KEY: "{JWT_SECRET_KEY}"
memoryLimit: 100
