_id: 653663794f6554002c943fae
name: Leader Users
language: javascript
timeout: 60
triggers:
  setLeaderUsers:
    type: schedule
    active: false
    options:
      timezone: Turkey
      frequency: 59 23 * * *
  getTopUsers:
    options:
      method: Get
      path: /getTopUsers
      preflight: true
    type: http
    active: false
env:
  SECRET_APIKEY: "{SECRET_APIKEY}"
  USER_BUCKET: "{USER_BUCKET}"
  LEADER_USERS_BUCKET: "{LEADER_USERS_BUCKET}"
  NO_DEVKIT_DATABASE_WARNING: "{NO_DEVKIT_DATABASE_WARNING}"
  PAST_MATCHES_BUCKET: "{PAST_MATCHES_BUCKET}"
memoryLimit: 100
order: 22
