_id: 66fe58b6030b4e002c618a93
name: New Turkcell User Flow
language: javascript
timeout: 60
triggers:
  default:
    type: http
    active: true
    options:
      method: Get
      path: /
      preflight: true
env:
  TCELL_ADMIN_BUCKET_INSERT_APIKEY: "{TCELL_ADMIN_BUCKET_INSERT_APIKEY}"
memoryLimit: 100
