_id: 6067935ee9960e002c27877f
title: Configuration
description: Describe your new bucket
icon: view_stream
primary: key
readOnly: false
history: false
properties:
  key:
    type: string
    title: key
    description: Description of the key input
    options:
      position: bottom
      translate: false
      unique: true
  value:
    type: string
    title: value
    description: Description of the value input
    options:
      position: bottom
acl:
  write: true==true
  read: true==true
order: 14
required:
  - key
